---

- name: httpd assignment
  hosts: all
  remote_user: ansible
  become: true


  tasks:  
      - name: Install httpd
        yum:
            name: httpd
            state: latest

      - name: page
        copy:
           content: " Hello txtkrnl\n"
           dest: /var/www/html/index.html

      - name: enable firewall
        firewalld:
           service: httpd
           state: enabled
           immediate: yes
           permanent: yes

      - name: start httpd
        service:
            name: httpd
            state: started
            enabled: true

