---

- name: httpd assignment
  hosts: webservers
  remote_user: ansible
  become: true


  tasks:  
      - name: Install httpd
        yum:
            name: httpd
            state: latest


      - name: page
        copy:
           content: " Hello txtkrnl\n"
           dest: /var/www/html/index.html


      - name: start httpd
        service:
            name: httpd
            state: started
            enabled: true

      - name: Enable firewalld
        service: name=firewalld state=started enabled=yes

      - name: Set dmz as default policy
        command: firewall-cmd --set-default-zone=dmz

      - name: Allow http/https
        command: firewall-cmd --zone=dmz --permanent --add-service=http --add-service=https
      
      - name: install wget
        yum:
           name: wget
           state: latest
      
      - name: Install Netdata
        shell: |
         curl -Ss -o kickstart-static64.sh https://my-netdata.io/kickstart-static64.sh
         chmod 750 kickstart-static64.sh
         ./kickstart-static64.sh --non-interactive

      - name: Allow netdata trafic
        command : firewall-cmd --permanent --zone=public --add-port=19999/tcp
