- name: httpd assignment
  hosts: webservers
  remote_user: ansible
  become: true


  tasks:
      - name: Install httpd
        yum:
            name: httpd
            state: latest

      - name: page
        copy:
           content: " Hello txtkrnl\n"
           dest: /var/www/html/index.html


      - name: start httpd
        service:
            name: httpd
            state: started
            enabled: true
